repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0

    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [--line-length=120]
